#!/usr/bin/env bash

exec >&2 6>&1

mkdir -p /var/tmp/influxdb-dump
chown gonano:gonano -R /var/tmp/influxdb-dump

/data/bin/influxd backup -database gonano /var/tmp/influxdb-dump

tar c -C /var/tmp/influxdb-dump . >&6

rm -rf /var/tmp/influxdb-dump
