#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# This hook will export the data to the new members while the service is offline

# export influxdb
execute "send diff data to new member" do
  command "rsync \
    --delete \
    -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' \
    -a /data/var/db/influxdb/. \
    #{payload[:member][:local_ip]}:/data/var/db/influxdb/"
end
