#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'
require 'json'

include Hooky::Influxdb

config = converge( CONFIG_DEFAULTS, payload[:config] )

users = config[:users]
port = config[:http_bind_address].split(":")[1] # 8086

plan = {
  behaviors: [:migratable, :backupable],
  redundant: false,
  horizontal: false,
  user: "nanobox",
  users: users,
  ips: [:default],
  port: port
}

puts JSON.pretty_generate(plan)
