#!/usr/bin/env bash

exec 6<&0

mkdir -p /var/tmp/influxdb-restore
chown -R gonano:gonano /var/tmp/influxdb-restore

tar x -C /var/tmp/influxdb-restore <&6

sv stop influxdb

/data/bin/influxd restore -metadir /var/lib/influxdb/meta /var/tmp/influxdb-restore
/data/bin/influxd restore -database gonano -datadir /var/lib/influxdb/data /var/tmp/influxdb-restore
chown -R influxdb:influxdb /var/lib/influxdb

sv start influxdb

rm -rf /var/tmp/influxdb-restore
