#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Import service (and start)
directory '/etc/service/influxdb' do
  recursive true
end

directory '/etc/service/influxdb/log' do
  recursive true
end

template '/etc/service/influxdb/log/run' do
  mode 0755
  source 'log-run.erb'
  variables ({ svc: "influxdb" })
end

template '/etc/service/influxdb/run' do
  mode 0755
  variables ({ exec: "influxd -config /data/etc/influxdb/influxdb.conf 2>&1" })
end

service 'influxdb' do
  action :enable
  init :runit
end

ensure_socket 'influxdb' do
  port '8086' # TODO: use configurable, or make not configurable in boxfile
  action :listening
end

# Import kapacitor service (and start)
directory '/etc/service/kapacitor' do
  recursive true
end

directory '/etc/service/kapacitor/log' do
  recursive true
end

template '/etc/service/kapacitor/log/run' do
  mode 0755
  source 'log-run.erb'
  variables ({ svc: "kapacitor" })
end

template '/etc/service/kapacitor/run' do
  mode 0755
  variables ({ exec: "kapacitord -config /data/etc/kapacitor/kapacitor.conf 2>&1" })
end

service 'kapacitor' do
  action :enable
  init :runit
end

# Attach the IP if provided
if payload[:ips]
  # set up persistance
  file "/etc/nanoinit.d/eth00" do
    content <<-EOF
#!/bin/bash
case $1 in
  start)
    if [[ ! $(ifconfig) =~ eth0:0 ]]; then
      ifconfig eth0:0 #{payload[:ips][:default]}
      arping -A -c 10 -I eth0 #{payload[:ips][:default]}
    fi
    ;;
  stop)
    if [[ $(ifconfig) =~ eth0:0 ]]; then
      ifconfig eth0:0 down
    fi
    ;;
  *)
    echo "$0 start|stop"
    exit 1
    ;;
esac
EOF
    mode 0755
  end

  # bring up interface
  execute "bring up vip" do
    command <<-EOF
      /etc/nanoinit.d/eth00 start
    EOF
  end
end
